apiVersion: v2
name: identity-service
description: Helm chart for Identity Service
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: microservice
    version: 0.1.0
    repository: "file://../../../charts/microservice"
